Update initializer.yml

diff --git a/.github/workflows/initializer.yml b/.github/workflows/initializer.yml
--- a/.github/workflows/initializer.yml
+++ b/.github/workflows/initializer.yml
@@ -40,14 +40,28 @@ jobs:
         id: vars
         run: echo "branch=initialize-repo-$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT
 
-      - name: Replace {reponame} and {username} with actual values
+      - name: Create develop branch if it doesn't exist
+        run: |
+          # Check if develop branch exists
+          if ! git ls-remote --heads origin develop | grep develop; then
+            echo "Creating develop branch from main..."
+            git checkout -b develop
+            git push -u origin develop
+            git checkout main  # Return to main branch for the rest of the workflow
+          else
+            echo "Develop branch already exists."
+          fi
+
+      - name: Replace {reponame} and {username} with actual values in non-workflow files
         run: |
           REPO_NAME_ONLY="${{ steps.extract.outputs.reponame }}"
           USERNAME="${{ steps.extract.outputs.username }}"
           REPO_NAME_ESCAPED=$(echo $REPO_NAME_ONLY | sed 's/\//\\\//g')
           USERNAME_ESCAPED=$(echo $USERNAME | sed 's/\//\\\//g')
-          find . -type f -exec sed -i "s/{reponame}/$REPO_NAME_ESCAPED/g" {} +
-          find . -type f -exec sed -i "s/{username}/$USERNAME_ESCAPED/g" {} +
+          
+          # Modify all files except workflow files
+          find . -type f -not -path "./.git/*" -not -path "./.github/workflows/*" -exec sed -i "s/{reponame}/$REPO_NAME_ESCAPED/g" {} \;
+          find . -type f -not -path "./.git/*" -not -path "./.github/workflows/*" -exec sed -i "s/{username}/$USERNAME_ESCAPED/g" {} \;
 
       - name: Remove initializer workflow
         run: |
@@ -57,7 +71,13 @@ jobs:
         run: |
           BRANCH_NAME="${{ steps.vars.outputs.branch }}"
           git checkout -b $BRANCH_NAME
-          git add .
+          
+          # Exclude workflow files to avoid permission errors
+          git add --all -- ':!.github/workflows'
+          
+          # Explicitly add the deletion of the initializer workflow
+          git add .github/workflows/initializer.yml
+          
           git commit -m "Initialize repository with repo name ${{ steps.extract.outputs.reponame }} and username ${{ steps.extract.outputs.username }}"
           git push origin HEAD:$BRANCH_NAME
 
